### ISSUE TITLE
Submenu Z-Index borked

### ISSUE THREAD

**Issue by eaton** [kbravh/netlify-cms-widget-nested-select#15]
Great widget! Thanks for the excellent work. Noticed when setting up a site with it that if the nested-select widget comes before any _other_ widgets in the config, the dynamically populated dropdown for the second, third, etc tier options appear underneath the next widget in the document's Z-order.

<img width="681" alt="nested-select-z" src="https://user-images.githubusercontent.com/46423/100047902-2eb99700-2dd9-11eb-92dc-ebfb053904df.png">

Haven't had a chance to dig very deep into it, but wanted to put a pin in it in case others have encountered the issue.

**Comment by kbravh** [comment]
@eaton Glad you like the widget! Thanks for catching this bug. The z-index was unset on the second menu, so fixing it was as simple as setting a z-index. 

The demo has been updated and version 1.0.3 of the package should include this fix.
